version: "3.0"
services:
  elasticsearch:
    container_name: elastic-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        hard: -1
        soft: -1
    restart: unless-stopped

  kibana:
    container_name: kibana-container
    image: docker.elastic.co/kibana/kibana:7.6.2
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
    restart: unless-stopped

  logstash:
    container_name: logstash-container
    image: docker.elastic.co/logstash/logstash:7.6.2
    command: bash -c "cd bin && logstash-plugin install logstash-input-mongodb && logstash-plugin install logstash-output-elasticsearch && logstash -f /usr/share/logstash/config/logstash.conf"
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/config/logstash.conf
    depends_on:
      - elasticsearch
      - mongodb
    networks:
      - es-net

  mongodb:
    container_name: mongo-container
    image: mongo:6-jammy
    ports:
      - 27017:27017
    volumes:
      - dbdata:/data/db
    networks:
      - mongo-net
    restart: unless-stopped

  mongo-express:
    container_name: mongo-express-container
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: "27017"
    ports:
      - 8081:8081
    networks:
      - mongo-net
    depends_on:
      - mongodb
    restart: unless-stopped

  backend:
    container_name: backend-container
    build:
      context: .
    ports:
      - 8071:8071
    networks:
      - mongo-net
      - es-net
    restart: unless-stopped

  redis:
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data
    restart: unless-stopped

volumes:
  esdata:
  dbdata:
    driver: local
  cache:
    driver: local

networks:
  es-net:
    driver: bridge
  mongo-net:
